album/urls.py
# from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.contrib import admin
from django.urls import path, include
from album import views

urlpatterns = [
    path('', views.base, name='base'),
    path('vista', views.first_view, name='first-view'),
    path('category/', views.category, name='category-list'),
    path('category/<int:category_id>/detail/', views.category_detail, name='category-detail'),
    
    path('photo/', views.PhotoListView.as_view(), name='photo-list'),
    # Aqui se proteje con contraseña y usuario, por URL
    path('photo/<int:pk>/detail/', login_required(views.PhotoDetailView.as_view()), name='photo-detail'),

    # Update
    path('photo/<int:pk>/update/', views.PhotoUpdate.as_view(), name='photo-update'),    
    # Create     
    path('photo/create/', views.PhotoCreate.as_view(), name='photo-create'),
    # Delete
    path('photo/<int:pk>/delete/', views.PhotoDelete.as_view(), name='photo-delete'),
]

# http://127.0.0.1:8000/album/category/2/detail/
# http://127.0.0.1:8000/album/photo/2/detail/

appFotos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
from album import views
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('username', 'email')
        # fields = ('url', 'username', 'email', 'is_staff')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('album/', include('album.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api', include(router.urls)),    
]

album/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver 
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Photo(models.Model):
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.PROTECT)
    title    = models.CharField(max_length=50, default='No tittle')
    photo    = models.ImageField(upload_to='photos/')
    pub_date = models.DateField(auto_now_add=True)
    favorite = models.BooleanField(default=False)
    comment  = models.CharField(max_length=200, blank=True)

    def __str__(self):
        return self.title
    
@receiver(post_delete, sender=Photo)
def photo_delete(sender, instance, **kwargs):
    # Borra los ficheros de las fotos que se eliminan
    instance.photo.delete(False);
    
def get_absolute_url(self):
    return reverse('photo-list')

# las clases representan las tablas en nuestra 
# data base 
# por tanto las columnas estan representadas por 
# las instancias de Field

album/views.py
from django.shortcuts import render
from django.http import HttpResponse
from album.models import Category, Photo
from django.views.generic import ListView, DetailView
#from django.core.urlresolvers import reverse_lazy
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

# HttpRequest, en el que va la información referente a la solicitud
# que estamos haciendo, como por ejemplo si el método empleado es POST o GET


def first_view(request):
    return HttpResponse('Esta es mi primera vista!')

def category(request):
    category_list = Category.objects.all()
    context = {'object_list': category_list}
    return render(request, 'album/category.html', context)


def category_detail(request, category_id):
    category = Category.objects.get(id=category_id)
    context = {'object': category}
    return render(request, 'album/category_detail.html', context)

# Vistas basadas en clases 
class PhotoListView(LoginRequiredMixin, ListView):
    model = Photo

class PhotoDetailView(DetailView):
    model = Photo

# Template base 
# Aqui se proteje todo con contraseña
@login_required(login_url='/accounts/login/')
def base(request):
    return render(request, 'base.html')

class PhotoUpdate(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = "__all__"
    success_url = reverse_lazy('photo-list')

class PhotoCreate(LoginRequiredMixin, CreateView):
    model = Photo
    fields = "__all__"
    success_url = reverse_lazy('photo-list')

class PhotoDelete(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo-list')

album/templates/adminlte/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block title_outer %}
        <title>{% block title %}{{ site.name }}{% endblock %}</title>
    {% endblock %}

    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% endblock %}

    {% block stylesheets %}
        {% include 'adminlte/lib/_styles.html' %}
    {% endblock %}

    {% block extra_head %}{% endblock %}
</head>
<body class="hold-transition skin-blue sidebar-mini {% block body_class %}{% block bodyclass %}{% endblock %}{% endblock %}">

{% block body %}
    <div class="wrapper">
        {% block nav_header %}
            {% include 'adminlte/lib/_main_header.html' %}
        {% endblock %}

        {% block nav_sidebar %}
            {% include 'adminlte/lib/_main_sidebar.html' %}
        {% endblock %}

        {% block content_wrapper %}
        <div class="content-wrapper">
            {% block content_header %}
                <section class="content-header">
                    {% block no_heading %}
                        <h1>
                            {% block page_name %}{% endblock %}
                            <div class="header-actions">
                                {% block page_actions %}{% endblock %}
                            </div>
                            {% block no_description %}
                            <small>{% block page_description %}{% endblock %}</small>
                            {% endblock %}
                        </h1>
                        {% block breadcrumbs %}
                            {# Breadcrumb implementation left to developers #}
                        {% endblock %}
                    {% endblock no_heading %}
                </section>
            {% endblock %}

            {% block content_outer %}
            <section class="content">
                {% block messages %}
                    {% include 'adminlte/lib/_messages.html' %}
                {% endblock %}

                {% block content_block_wrap %}
                    {% block content %}{% endblock %}
                {% endblock %}
            </section>
            {% endblock %}

        </div>
        {% endblock content_wrapper %}

        {% block nav_footer %}
            {% include 'adminlte/lib/_main_footer.html' %}
        {% endblock %}

    </div>
{% endblock body %}

{% block javascript %}
    {% include 'adminlte/lib/_scripts.html' %}
{% endblock %}

{% block extra_foot %}{% endblock %}
</body>
</html>

album/templates/adminlte/components/info_box.html
{% load humanize %}
<div class="info-box bg-{{ color }}">
    {% if not hide_icon %}
        <span class="info-box-icon"><i class="fa fa-{{ icon }}"></i></span>
    {% endif %}
    <div class="info-box-content">
        <span class="info-box-text">{{ header }}</span>
        <span class="info-box-number">{{ number }} {{ unit }}</span>
        {% if percent %}
            <div class="progress">
                <div class="progress-bar" style="width: {{ percent }}%"></div>
            </div>
            {% if how_long %}
                <span class="progress-description">
                    {{ percent }}% Increase in {{ how_long }}
                </span>
            {% endif %}
        {% endif %}
    </div><!-- /.info-box-content -->
</div><!-- /.info-box -->

album/templates/adminlte/example.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Title</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip"
                        title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            Start creating your amazing application!
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
            Footer
        </div>
        <!-- /.box-footer-->
    </div>
    <!-- /.box -->
{% endblock %}

album/templates/adminlte/index.html
{% extends 'adminlte/base.html' %}

{% block content %}

{% endblock %}

album/templates/adminlte/lib/_main_footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        {% block footer_right %}
            <b>Version</b> {% block version %}0.1{% endblock %}
        {% endblock %}
    </div>

    {% block footer_left %}
    {% block legal %}
    <strong>Copyright &copy; {% now "Y" %}{% if not site %}.{% endif %}
        {% if site %}
            <a href="http://{{ site.domain }}">{{ site.name }}</a>
        {% endif %}
    </strong>
    {% endblock %}
    {% endblock %}
</footer>

album/templates/adminlte/lib/_main_header.html
{% load adminlte_helpers i18n %}
<header class="main-header">
    <!-- Logo -->
    {% block logo %}
    <a href="{% block logo_href %}/{% endblock %}" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini">{% block logo_text_small %}<b>A</b>LTE{% endblock %}</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg">{% block logo_text %}<b>Admin</b>LTE{% endblock %}</span>
    </a>
    {% endblock %}

    <!-- Header Navbar: style can be found in header.less -->
    {% block nav_bar %}
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>

        {% block nav_bar_center %}{% endblock %}

        {% block nav_custom_menu %}
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                {% block header_dropdowns %}
                    {% if request.user.is_authenticated %}
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{% avatar_url size=50 %}" class="user-image" alt="User Image">
                                <span class="hidden-xs">{% firstof request.user.get_short_name request.user.get_username %}</span>
                            </a>
                            <ul class="dropdown-menu">
                                {% block user_header %}
                                <li class="user-header">
                                    <img src="{% avatar_url size=180 %}" class="img-circle" alt="User Image">
                                    <p>
                                        {% firstof request.user.get_short_name request.user.get_username %}
                                        <small>Member since {{ request.user.date_joined }}</small>
                                    </p>
                                </li>
                                {% endblock %}

                                <!-- Menu Footer-->
                                {% block menu_footer %}
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{% block change_password_url %}{% url 'admin:password_change' %}{% endblock %}"
                                           class="btn btn-default btn-flat">{% trans 'Change password' %}</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{% block logout_url %}{% logout_url %}{% endblock %}" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                                {% endblock %}

                            </ul>
                        </li>
                    {% endif %}
                {% endblock header_dropdowns %}
            </ul>
        </div>
        {% endblock nav_custom_menu %}
    </nav>
    {% endblock %}
</header>

album/templates/adminlte/lib/_main_sidebar.html
{% load adminlte_helpers %}
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        {% block user_panel %}
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{% avatar_url size=90 %}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{% firstof request.user.get_full_name request.user.username %}</p>
            </div>
        </div>
        {% endblock %}

        {% block form %}{% endblock %}

        <!-- sidebar menu: : style can be found in sidebar.less -->
        {% block nav_links_ul %}
        <ul class="sidebar-menu">
            {% block nav_links_outer %}
            <li class="header">{% block nav_heading %}Inicio{% endblock %}</li>

            {% block nav_links %}
                <li>
                    <a href="{% url "category-list" %}">
                        <i class="fa fa-dashboard"></i> <span>Category</span>
                    </a>            
                </li>
                <li>
                    <a href="{% url "photo-list" %}">
                        <i class="fa fa-user"></i> <span>Photos</span>
                    </a>
                </li>
            {% endblock nav_links %}
            {% endblock nav_links_outer %}
        </ul>
        {% endblock nav_links_ul %}
    </section>
    <!-- /.sidebar -->
</aside>

album/templates/adminlte/lib/_messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
        <div class="alert alert-success alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% else %}
        <div class="alert alert-info alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endif %}
    {% endfor %}
{% endif %}

album/templates/adminlte/lib/_pagination.html
{% if pager and ROOT_MENU.current_menu.view_name %}
    <ul class="pagination pagination-sm no-margin pull-right">
        <li><a href="{% url ROOT_MENU.current_menu.view_name %}?page=1&{{ pager.url_params }}">&laquo;</a></li>
        {% if pager.page > 2 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-2}}&{{ pager.url_params }}">
                    {{ pager.page | add:-2 }}
                </a>
            </li>
        {% endif %}
        {% if pager.page > 1 %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:-1}}&{{ pager.url_params }}">
                    {{ pager.page | add:-1 }}
                </a>
            </li>
        {% endif %}
        <li class="active"><a href="#">{{ pager.page }}</a></li>
        {% if pager.has_next %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:1}}&{{ pager.url_params }}">
                    {{ pager.page | add:1 }}
                </a>
            </li>
        {% endif %}
        {% if pager.has_next_two %}
            <li>
                <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.page|add:2}}&{{ pager.url_params }}">
                    {{ pager.page | add:2 }}
                </a>
            </li>
        {% endif %}
        <li>
            <a href="{% url ROOT_MENU.current_menu.view_name %}?page={{pager.last_page}}&{{ pager.url_params }}">
            &raquo;
            </a>
        </li>
    </ul>
{% endif %}

album/templates/adminlte/lib/_scripts.html
{% load static %}

{% block scripts %}
<script src="{% static "jquery/dist/jquery.min.js" %}"></script>
<script src="{% static "jquery/dist/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static "bootstrap/dist/js/bootstrap.min.js" %} "></script>
<script src="{% static "admin-lte/dist/js/app.min.js" %}"></script>
{% endblock %}

album/templates/adminlte/lib/_styles.html
{% load static %}

{% block styles %}
<link rel="stylesheet" type="text/css" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" type="text/css" href="{% static "admin-lte/dist/css/AdminLTE.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "admin-lte/dist/css/skins/_all-skins.min.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "icheck/skins/square/blue.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "conflicts/conflicts.css" %}">
{% endblock %}

album/templates/adminlte/login.html
{% extends "adminlte/base.html" %}
{% load i18n static %}

{% block body_class %}login-page{% endblock %}

{% block body %}
    <div class="login-box">
        {% block logo %}
        <div class="login-logo">
            {# Mirrors block names used in _main_header.html #}
            <a href="{% block logo_href %}/{% endblock %}">{% block logo_text %}<b>Admin</b>LTE{% endblock %}</a>
        </div>
        {% endblock %}
        <!-- /.login-logo -->
        <div class="login-box-body">
            {% block login_errors %}
                {% if form.errors and not form.non_field_errors %}
                    <p class="alert alert-danger">
                        {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                            {% trans "Please correct the errors below." %}{% endif %}
                    </p>
                {% endif %}

                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger">
                            {{ error }}
                        </p>
                    {% endfor %}
                {% endif %}
            {% endblock login_errors %}

            {% block login_form %}
                <form action="" method="post">
                    {% csrf_token %}
                    {% if message %}
                        <p class="login-box-msg" style="color: red;">{{ message }}</p>
                    {% endif %}
                    <div class="form-group has-feedback">
                        <input name="username" class="form-control" placeholder="Username">
                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    </div>
                    <div class="form-group has-feedback">
                        <input type="password" name="password" class="form-control" placeholder="Password">
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>
                    <div class="row">
                        <div class="col-xs-8">
                            {% block login_form_links %}
                            {% endblock %}
                        </div>
                        <div class="col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Login</button>
                        </div>
                    </div>
                </form>
            {% endblock login_form %}

        </div>
    </div>
{% endblock %}

album/templates/adminlte/pages/edit.html
{% extends 'adminlte/base.html' %}

{% block header_tail %}
    <script type="text/javascript" charset="utf-8" src="/static/plugins/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/static/plugins/ueditor/ueditor.all.min.js"> </script>
    <!--建议手动加在语言，避免在ie下有时因为加载语言失败导致编辑器加载失败-->
    <!--这里加载的语言文件会覆盖你在配置项目里添加的语言类型，比如你在配置项目里配置的是英文，这里加载的中文，那最后就是中文-->
    <script type="text/javascript" charset="utf-8" src="/static/plugins/ueditor/lang/zh-cn/zh-cn.js"></script>
{% endblock %}

{% block content %}
    <div class="box">
        <!-- form start -->
        <form role="form" method="post">{% csrf_token %}
            <div class="box-body">
                <div class="form-group">
                    <label for="title">标题</label>
                    <input id="title" name="title" class="form-control" value="{{ page.title }}" />
                </div>
                <div class="form-group">
                    <label>正文</label>
                    <script id="editor" type="text/plain" style="width:768px;height:500px;">{{ page.content | safe }}</script>
                </div>
            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary">提交</button>
            </div>
        </form>
    </div>
    <!-- /.box -->
{% endblock %}

{% block body_tail %}
    <script>
        //实例化编辑器
        //建议使用工厂方法getEditor创建和引用编辑器实例，如果在某个闭包下引用该编辑器，直接调用UE.getEditor('editor')就能拿到相关的实例
        var ue = UE.getEditor('editor', {
            textarea: 'content',
            customstyle: [
                {
                    tag: 'img',
                    name: 'img',
                    label: '',
                    style: 'width: 100%;'
                }
            ]
        });
    </script>
{% endblock %}

album/templates/adminlte/pages/index.html
{% extends 'adminlte/base.html' %}

{% block content %}
    <div class="box">
        <div class="box-body">
            <table class="table table-bordered">
                <tr>
                    <th>#</th>
                    <th>页面URL</th>
                    <th>操作</th>
                </tr>
                {% for page in pager.items %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a target="_blank" href="{% url 'adminlte.example.pages' page_id=page.id %}">{{ page.title }}</a></td>
                        <td><a href="{% url 'adminlte.example.page.edit' page_id=page.id %}">编辑</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
            {% include 'adminlte/lib/_pagination.html' %}
        </div>
    </div>
{% endblock %}

album/templates/album/category.html
{% extends 'adminlte/base.html' %}

{% block section %}
    <h2>Category</h2>
    <hr>
{% endblock section %}
{% block maincontent %}
<div>
    {% for c in object_list %}
        <a href="{% url 'category-detail' c.pk %}">
            {{ c.name }}
        </a>
    {% endfor %}
</div>
{% endblock maincontent %} 

album/templates/album/category_detail.html
{% extends 'adminlte/base.html' %}

{% load static %}
{% block section %}
<h2>{{ object.name }}</h2>
<hr>
{% endblock section %}
{% block maincontent %}
<div>
    <tableborder="1px">
        <tr>
            {% for p in object.photo_set.all %}
            <td>
                <div>{{ p.title }}</div>
                <div>
                    <a href="{% url "photo-detail" p.id %}">
                        <img src="{% static p.photo.url %}" style="width:200px;height:200px" />
                    </a>
                </div>
            </td>
            {% endfor %}
        </tr>
    </table> 
</div>
{% endblock maincontent %} 

album/templates/album/category_list.html
{% extends 'adminlte/base.html' %}

{% block section %}
    <h2>Category</h2>
    <hr>
{% endblock section %}

{% block maincontent %}
<div>
    {% for c in object_list %}
        <a href="{% url 'category-detail' c.pk %}">
            {{ c.name }}
        </a>
    {% endfor %}
</div>
{% endblock maincontent %} 

album/templates/album/photo_confirm_delete.html
{% extends 'adminlte/base.html' %} 

{% block maincontent %}
    <form action="" method="post">{% csrf_token %}
    <p>Delete "{{ object.title }}"?</p>
    <input type="submit" value="Confirm" />
    <a class='btn' href="{% url 'photo-list' %}">Cancel</a>
    </form>
{% endblock maincontent %} 

album/templates/album/photo_detail.html
{% extends 'adminlte/base.html' %}
{% load static %}

{% block content %}
   <h2>
      {{ object }}

      {% if object.favorite %}
         &#9733;
         {% else %}
         &#9734;
      {% endif %}

      {% if object.category_id %}
         ( <a href="{% url 'category-detail' object.category_id %}"> {%
            object.title %} </a> )
      {% endif %}
   </h2>

   <p><strong>comments: </strong>{{ object.comment|default:"no comments" }}</p>

   <a href="{% url "photo-update" object.id %}">edit</a>
   <a href="{% url "photo-delete" object.id %}">delete</a>
   <hr>

   <div>
      <div>
         <img src= "{% static object.photo.url %}" style="width:550px;height:420px" />
      </div>
   </div>
{% endblock content %}

album/templates/album/photo_form.html
{% extends "adminlte/base.html" %}

{% block maincontent %}
    <form enctype="multipart/form-data" method="post">{% csrf_token %} {{ form.as_p }} 
        <button type="submit">Save</button>
        <a class='btn'href="{% url 'photo-list' %}">Cancel</a>
    </form>
{% endblock maincontent%}

album/templates/album/photo_list.html
{% extends 'adminlte/base.html' %}
{% load static %}

{% block section %}
    <h2>Photo</h2>
    <hr>
{% endblock section %}

{% block content %}
    <div class="row well">
        {% for p in object_list.all %}
        <div class="col-md-4 well">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ p.title }}</h3>
                </div>
                <div class="panel-body">
                    <a href="{% url 'photo-detail' p.id %}">
                        <img src="{% static p.photo.url %}" style="width:200px;height:200px;"/>
                    </a>
                </div>
                <div class="panel-footer">
                    {% if p.comment %}
                        {{ p.comment }}
                    {% else %}
                        <a href="{% url 'photo-update' p.id %}">edit comments</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div> 
{% endblock content %}

album/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
   <metacharset="UTF-8">
   <title>Album</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script> 
</head>
<body>   
   <nav class="navbar navbar-default">
      <div class="container-fluid"> 
         <div class="navbar-header">
            <button type="button"class="navbar-toggle collapsed" data-toggle="collapse"data-target="#bs-example-navbar-collapse-1">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'base' %}">Album</a>
         </div> 
         <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
               <li>
                  <a href="{% url 'category-list' %}">
                     Category 
                     <span class="sr-only">(current)</span>
                  </a>
               </li>
               <li>
                  <a href="{% url 'photo-list' %}">Photo</a>
               </li>
            </ul>
            
            <ul class="nav navbar-nav navbar-right">
               <li class="dropdown">
                  <a href="#"class="dropdown-toggle" data-toggle="dropdown"role="button"aria-expanded="false">Action
                  <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu"role="menu">
                     <li>
                        <a href="{% url 'photo-create' %}">Upload</a>
                     </li>
                     <li class="divider"></li>
                     <li><a href="#">Log In</a></li>
                  </ul>
               </li>
            </ul>
         </div>
      </div>
   </nav>
   <div class="container">
      {% block section %}
      {% endblock section %}
   </div>
   <div class="container">
      {% block maincontent %}
      {% endblock maincontent %}
   </div>
</body>
</html>